# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: claire osburn
email: claire.a.osburn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog and portfolio of Claire Osburn, Web Designer & Developer located in San Antonio. All thoughts are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://claireosburn.com" # the base hostname & protocol for your site
twitter_username: claireosburn436
github_username:  cosburn

# Build settings
markdown: kramdown
